### ISSUE TITLE
Customize ProgressBar

### ISSUE THREAD

**Issue by sandokan815** [lhz516/react-h5-audio-player#187]
HI, Thanks for sharing nice library for playing audio.
Could you let me know if this library supports customising progress bar?
i.e. progress bar different format(looking for image progress bar)

**Comment by lhz516** [comment]
You can do this to use image on your progress bar
```css
.rhap_progress-bar {
  background-image: url('something.jpg');
}
```
You may also want to adjust the height or something. Feel free to overwrite any CSS in your project.
