### ISSUE TITLE
Can the player be scaled down in size?

### ISSUE THREAD

**Issue by MirelesCloud** [lhz516/react-h5-audio-player#70]
Can the the player's font size and controls be sized down without adding custom controls?  I'm trying to display it in a table style horizontal format that is also mobile friendly.

**Comment by lhz516** [comment]
In this case, you may want to use css `transform` to scale the size.

```css
.rhap_container {
  transform: scale(0.7);
}
```
